name: Package driver distribution

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install build dependencies
        shell: bash
        run: |
          wget https://github.com/gbdk-2020/gbdk-2020/releases/download/4.1.1/gbdk-linux64.tar.gz -O- | tar xz
          sudo apt update
          sudo apt install rgbds

      - name: Check out hUGEDriver
        uses: actions/checkout@v2
        with:
          path: hUGEDriver

      - name: Build distribution
        shell: bash
        run: |
          export PATH=$PATH:`realpath gbdk/bin`
          pushd hUGEDriver
          rgbasm -DGBDK -ohUGEDriver.obj hUGEDriver.asm
          python .\tools\rgb2sdas.py -o hUGEDriver.o hUGEDriver.obj
          sdar -ru hUGEDriver.lib hUGEDriver.o
          popd hUGEDriver

          mkdir packaging
          mkdir packaging/rgbds
          mkdir packaging/gbdk

          cp hUGEDriver/hUGEDriver.asm packaging/rgbds/
          cp -R hUGEDriver/include/ packaging/
          cp hUGEDriver/hUGEDriver.asm packaging/gbdk/

      - name: Store build
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: packaging/
